/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Application.java to edit this template
 */
package main;

import java.awt.Graphics;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ELCOT
 */
public class adtrain extends javax.swing.JFrame {

    /**
     * Creates new form adtrain
     */
    public adtrain() {
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

	jPanel1 = new javax.swing.JPanel() {
	    public void paintComponent(Graphics g) {
		ImageIcon im = new ImageIcon("Images/2.jpeg");
		Image i = im.getImage();
		g.drawImage(i, 0, 0, this.getSize().width, this.getSize().height, this);
	    }
	};
	jLabel1 = new javax.swing.JLabel();
	jLabel2 = new javax.swing.JLabel();
	jLabel3 = new javax.swing.JLabel();
	jLabel4 = new javax.swing.JLabel();
	jLabel5 = new javax.swing.JLabel();
	jLabel6 = new javax.swing.JLabel();
	jLabel7 = new javax.swing.JLabel();
	jLabel8 = new javax.swing.JLabel();
	t1 = new javax.swing.JTextField();
	t2 = new javax.swing.JTextField();
	t3 = new javax.swing.JTextField();
	t4 = new javax.swing.JTextField();
	t5 = new javax.swing.JTextField();
	jButton1 = new javax.swing.JButton();
	jDateChooser1 = new com.toedter.calendar.JDateChooser();
	jLabel9 = new javax.swing.JLabel();
	t7 = new javax.swing.JTextField();
	jLabel10 = new javax.swing.JLabel();
	t6 = new javax.swing.JTextField();
	menuBar = new javax.swing.JMenuBar();
	jMenu5 = new javax.swing.JMenu();
	jCheckBoxMenuItem6 = new javax.swing.JCheckBoxMenuItem();
	jMenu1 = new javax.swing.JMenu();
	jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
	jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
	jMenu2 = new javax.swing.JMenu();
	jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
	jMenu3 = new javax.swing.JMenu();
	jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();
	jMenu7 = new javax.swing.JMenu();
	jCheckBoxMenuItem5 = new javax.swing.JCheckBoxMenuItem();

	setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

	jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
	jLabel1.setText("Welcome to Train Ticket Reservation  System");

	jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
	jLabel2.setText("Add Train");

	jLabel3.setText("Train Name");

	jLabel4.setText("Source");

	jLabel5.setText("Destination");

	jLabel6.setText("Date");

	jLabel7.setText("Departure Time");

	jLabel8.setText("Arrival Time");

	t2.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		t2ActionPerformed(evt);
	    }
	});

	t3.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		t3ActionPerformed(evt);
	    }
	});

	t4.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		t4ActionPerformed(evt);
	    }
	});

	t5.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		t5ActionPerformed(evt);
	    }
	});

	jButton1.setText("Add");
	jButton1.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		jButton1ActionPerformed(evt);
	    }
	});

	jLabel9.setText("Price");

	t7.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		t7ActionPerformed(evt);
	    }
	});

	jLabel10.setText("Seats");

	t6.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		t6ActionPerformed(evt);
	    }
	});

	javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
	jPanel1.setLayout(jPanel1Layout);
	jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
			.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(jPanel1Layout.createSequentialGroup().addGap(147, 147, 147).addGroup(jPanel1Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 346,
					javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
					.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
						.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122,
							javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 122,
							javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 122,
							javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 122,
							javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 122,
							javax.swing.GroupLayout.PREFERRED_SIZE))
					.addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING,
						javax.swing.GroupLayout.PREFERRED_SIZE, 122,
						javax.swing.GroupLayout.PREFERRED_SIZE)
					.addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING,
						javax.swing.GroupLayout.PREFERRED_SIZE, 122,
						javax.swing.GroupLayout.PREFERRED_SIZE)
					.addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING,
						javax.swing.GroupLayout.PREFERRED_SIZE, 122,
						javax.swing.GroupLayout.PREFERRED_SIZE))
					.addGap(18, 18, 18)
					.addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 203,
							javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE,
							211, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 203,
							javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, 203,
							javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, 203,
							javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 203,
							javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 203,
							javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 203,
							javax.swing.GroupLayout.PREFERRED_SIZE)))))
			.addGroup(jPanel1Layout.createSequentialGroup().addGap(260, 260, 260).addComponent(jLabel2,
				javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
			.addGroup(jPanel1Layout.createSequentialGroup().addGap(264, 264, 264).addComponent(jButton1)))
			.addContainerGap(218, Short.MAX_VALUE)));
	jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		.addGroup(jPanel1Layout.createSequentialGroup().addGap(31, 31, 31)
			.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
				javax.swing.GroupLayout.PREFERRED_SIZE)
			.addGap(9, 9, 9)
			.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
				javax.swing.GroupLayout.PREFERRED_SIZE)
			.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
			.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
				.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
					javax.swing.GroupLayout.PREFERRED_SIZE)
				.addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
					javax.swing.GroupLayout.PREFERRED_SIZE))
			.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
							javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
							javax.swing.GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
							javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
							javax.swing.GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
						javax.swing.GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13,
						Short.MAX_VALUE))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
					jPanel1Layout.createSequentialGroup()
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
							javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
							javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
			.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
				.addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
					javax.swing.GroupLayout.PREFERRED_SIZE)
				.addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
					javax.swing.GroupLayout.PREFERRED_SIZE))
			.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
			.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
				.addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
					javax.swing.GroupLayout.PREFERRED_SIZE)
				.addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
					javax.swing.GroupLayout.PREFERRED_SIZE))
			.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
			.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
				.addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
					javax.swing.GroupLayout.PREFERRED_SIZE)
				.addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
					javax.swing.GroupLayout.PREFERRED_SIZE))
			.addGap(18, 18, 18)
			.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
				.addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
					javax.swing.GroupLayout.PREFERRED_SIZE)
				.addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
					javax.swing.GroupLayout.PREFERRED_SIZE))
			.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
			.addComponent(jButton1).addGap(21, 21, 21)));

	jMenu5.setText("Home");

	jCheckBoxMenuItem6.setSelected(true);
	jCheckBoxMenuItem6.setText("Admin Home");
	jCheckBoxMenuItem6.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		jCheckBoxMenuItem6ActionPerformed(evt);
	    }
	});
	jMenu5.add(jCheckBoxMenuItem6);

	menuBar.add(jMenu5);

	jMenu1.setText("Train");

	jCheckBoxMenuItem1.setSelected(true);
	jCheckBoxMenuItem1.setText("Add");
	jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		jCheckBoxMenuItem1ActionPerformed(evt);
	    }
	});
	jMenu1.add(jCheckBoxMenuItem1);

	jCheckBoxMenuItem2.setSelected(true);
	jCheckBoxMenuItem2.setText("View");
	jCheckBoxMenuItem2.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		jCheckBoxMenuItem2ActionPerformed(evt);
	    }
	});
	jMenu1.add(jCheckBoxMenuItem2);

	menuBar.add(jMenu1);

	jMenu2.setText("Bookings");

	jCheckBoxMenuItem3.setSelected(true);
	jCheckBoxMenuItem3.setText("View Bookings");
	jCheckBoxMenuItem3.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		jCheckBoxMenuItem3ActionPerformed(evt);
	    }
	});
	jMenu2.add(jCheckBoxMenuItem3);

	menuBar.add(jMenu2);

	jMenu3.setText("Users");

	jCheckBoxMenuItem4.setSelected(true);
	jCheckBoxMenuItem4.setText("View Users");
	jCheckBoxMenuItem4.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		jCheckBoxMenuItem4ActionPerformed(evt);
	    }
	});
	jMenu3.add(jCheckBoxMenuItem4);

	menuBar.add(jMenu3);

	jMenu7.setText("Logout");

	jCheckBoxMenuItem5.setSelected(true);
	jCheckBoxMenuItem5.setText("Logout");
	jCheckBoxMenuItem5.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		jCheckBoxMenuItem5ActionPerformed(evt);
	    }
	});
	jMenu7.add(jCheckBoxMenuItem5);

	menuBar.add(jMenu7);

	setJMenuBar(menuBar);

	javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	getContentPane().setLayout(layout);
	layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
		jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
		javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
	layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
		jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

	pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_t2ActionPerformed
	// TODO add your handling code here:
    }// GEN-LAST:event_t2ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_t3ActionPerformed
	// TODO add your handling code here:
    }// GEN-LAST:event_t3ActionPerformed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_t4ActionPerformed
	// TODO add your handling code here:
    }// GEN-LAST:event_t4ActionPerformed

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_t5ActionPerformed
	// TODO add your handling code here:
    }// GEN-LAST:event_t5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
	try {
	    String tname = t1.getText();
	    String src = t2.getText();
	    String des = t3.getText();

	    Date d = jDateChooser1.getDate();
	    // getTime() but y give getDate()
	    java.sql.Date date2 = new java.sql.Date(d.getTime());
	    String dep = t4.getText();
	    Date d1 = new SimpleDateFormat("hh:mm:ss a").parse(dep);
	    java.sql.Time d2 = new java.sql.Time(d1.getTime());
	    String arr = t5.getText();
	    // SimpleDateFotmat but you give SimpleTimeFormat
	    Date d3 = new SimpleDateFormat("hh:mm:ss a").parse(arr);
	    java.sql.Time d4 = new java.sql.Time(d3.getTime());
	    String sea = t6.getText();
	    String pri = t7.getText();
	    Class.forName("com.mysql.cj.jdbc.Driver");
	    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "");
	    PreparedStatement ps = con.prepareStatement(
		    "insert into train(Train_Name,Source,Destination,Date,Departure_Time,Arrival_Time,Seats,Price)values(?,?,?,?,?,?,?,?)");
	    ps.setString(1, tname);
	    ps.setString(2, src);
	    ps.setString(3, des);
	    ps.setDate(4, date2);
	    ps.setTime(5, d2);
	    ps.setTime(6, d4);
	    ps.setString(7, sea);
	    ps.setString(8, pri);
	    int status = ps.executeUpdate();
	    if (status > 0) {
		JOptionPane.showMessageDialog(this, "Register Successfully");
		t1.setText("");
		t2.setText("");
		t3.setText("");
		t4.setText("");
		t5.setText("");
		t6.setText("");
		t7.setText("");

	    } else {
		JOptionPane.showMessageDialog(this, "Register Failed");
	    }
	}

	catch (ClassNotFoundException ex) {
	    Logger.getLogger(adtrain.class.getName()).log(Level.SEVERE, null, ex);
	} catch (SQLException ex) {
	    Logger.getLogger(adtrain.class.getName()).log(Level.SEVERE, null, ex);
	} catch (ParseException ex) {
	    Logger.getLogger(adtrain.class.getName()).log(Level.SEVERE, null, ex);
	}
    }// GEN-LAST:event_jButton1ActionPerformed

    private void t7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_t7ActionPerformed
	// TODO add your handling code here:
    }// GEN-LAST:event_t7ActionPerformed

    private void t6ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_t6ActionPerformed
	// TODO add your handling code here:
    }// GEN-LAST:event_t6ActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
	adtrain obj1 = new adtrain();
	obj1.setVisible(true);
	this.setVisible(false);
    }// GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void jCheckBoxMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jCheckBoxMenuItem2ActionPerformed
	view obj2 = new view();
	obj2.setVisible(true);
	this.setVisible(false);

    }// GEN-LAST:event_jCheckBoxMenuItem2ActionPerformed

    private void jCheckBoxMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jCheckBoxMenuItem3ActionPerformed
	BookingDetails obj10 = new BookingDetails();
	obj10.setVisible(true);
	this.setVisible(false);

    }// GEN-LAST:event_jCheckBoxMenuItem3ActionPerformed

    private void jCheckBoxMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jCheckBoxMenuItem4ActionPerformed
	ViewCustomer obj11 = new ViewCustomer();
	obj11.setVisible(true);
	this.setVisible(false);
    }// GEN-LAST:event_jCheckBoxMenuItem4ActionPerformed

    private void jCheckBoxMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jCheckBoxMenuItem5ActionPerformed
	Home ob = new Home();
	ob.setVisible(true);
	this.setVisible(false);
    }// GEN-LAST:event_jCheckBoxMenuItem5ActionPerformed

    private void jCheckBoxMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jCheckBoxMenuItem6ActionPerformed
	newreg h = new newreg();
	h.setVisible(true);
	this.setVisible(false);
    }// GEN-LAST:event_jCheckBoxMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
	// (optional) ">
	/*
	 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
	 * look and feel. For details see
	 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(adtrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(adtrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(adtrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(adtrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	// </editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new adtrain().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem5;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem6;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    // End of variables declaration//GEN-END:variables

}
